---
title: "Scoping Review Protocol: Statistical Models for Longitudinal Data"
date: "`r Sys.Date()`"
author: "Ariel I. Mundo Ortiz"
affiliation: "Université de Montréal, Montreal, QC, Canada"
format:
  pdf:
    keep-tex: true
    documentclass: article
    toc: true
    number-sections: true
    colorlinks: true
    csl: references/american-medical-association.csl
    bibliography: references/refs.bib
---

## Background

Longitudinal studies are frequently used in the health sciences (biomedical research, epidemiology, public health, among others) as they allow to examine how the temporal effect of a treatment or intervention. Despite their benefits, the inherent time dependency of longitudinal studies creates additional challenges with regard to data missingness, financial costs, and more importantly, the selection statistical methodologies that are appropriate to analyze the collected signal [@caruana2015;@mundo2022].

In this regard, statistical methods such as the repeated measures analysis of variance (rm-ANOVA) or linear mixed models (LMMs) have been historically preferred by researchers, but the assumptions required for their use are frequently not satisfied in longitudinal studies in the health sciences [@mundo2022]. Although 

## field


good number to start between 5-10k
 
rationales for the methods used
 
how many papers use each method, or improved method
 
software, why people use what they use
 
reasons for why people use the same methods
 
 
 
 


##  Objective

This study aims to report the different statistical models used in the health sciences to analyze longitudinal data, in order to present anunderstand the rationale for the choices used by the majority of researchers. In this way, the use of such models can be contextualized and the implications of such choices can be analyzed.  

_checking how many people check for model assumptions and how this impacts the results they report_

## Review Question

## Databases

## Search Terms

## Criteria

### Inclusion Criteria

- methods paper see new methods developed 

- application

### Exclusion Criteria

### Additional Resources

### Comparison (?)

## Data Extraction

### Data Synthesis Strategy

# References

::: {#refs}
:::